### ISSUE TITLE
Feature Request: debug option so i can check for false positives

### ISSUE THREAD

**Issue by muescha** [retextjs/retext-syntax-mentions#9] opened 2020-06-15 17:44 UTC
### Subject of the feature

allow an option `debug` or similar, which prints a warning with the replaced positions. then i can check for false positives

### Problem

sometimes the mentions are not twitter handles and should be more a code block

for example 

```markdown
you can use the @reac/router component
```

### Expected behavior

i see a warning about the replaced snippets

**Comment by wooorm** [comment] 2020-06-15 17:50
I’m sorry, I don’t understand the question? 🤔

**Comment by muescha** [comment] 2020-06-15 18:08
for each replacement it makes here:

https://github.com/retextjs/retext-syntax-mentions/blob/66dc99aa0af3876429d69b6c181a0b0c8b26525e/index.js#L61-L68

Example: 

```javascript
.use(require("retext-syntax-mentions"), { warning: true})
```

for this text: 
```markdown
this is text which uses @react/router in the text.
```

an reporter can print this warning:
```
line 1:24-37
warning:  `@react/router` is identified as a mention
```

**Comment by wooorm** [comment] 2020-06-16 10:48
I don’t think it’s wise to add debugging steps for the intended behavior of the 300+ packages in the unified ecosystem. It’ll take months, increase bundle size a lot, and impact performance negatively.

I suggest instead, to either:

1. Add `console.log` statement to files in `node_modules` yourself: this is a very versatile way to debug packages
2. A more generic solution, such as:
   ```js
   .use(() => (tree, file) { file.data.treeBefore = JSON.parse(JSON.stringify(tree)) })
   .use(intendedPlugin)
   .use(() => (tree) { console.log(someJsonDiffPackage(file.data.treeBefore, tree)) })

**Comment by muescha** [comment] 2020-06-16 11:06
yes - a general debug plugin would be the best solution.

**Comment by muescha** [comment] 2020-06-16 11:06
just to see the json diff is also not hat easy, i would like to see the x-lines before and after.

**Comment by muescha** [comment] 2020-06-16 11:09
maybe the debug-tool creates a vMessage for a position which is changed, and any reporter can later print the info...

**Comment by muescha** [comment] 2020-06-16 11:27
is there some handy tree (+ node) compare util?

**Comment by muescha** [comment] 2020-06-16 11:28
~~why there is this `JSON.parse(JSON.stringify(tree))` - what info strip it down - or is it "just" a deep copy?~~ yes deep copy

**Comment by ChristianMurphy** [comment] 2020-06-16 12:18
> is there some handy tree (+ node) compare util?

https://github.com/syntax-tree/unist-diff

**Comment by wooorm** [comment] 2020-06-16 15:45
Hmm, `unist-diff` is WIP though, was never finished. So I’d suggest JSON diffing, or use `unist-util-inspect` and diff the text.

**Comment by muescha** [comment] 2020-06-16 21:18
but in both cases i don't get a position?

**Comment by muescha** [comment] 2020-06-16 21:23
> unist-diff is WIP though, was never finished

at which place i can expect problems bc of unfinished

**Comment by wooorm** [comment] 2020-06-17 07:28
> but in both cases i don't get a position?

I don’t understand?

> at which place i can expect problems bc of unfinished

It doesn’t work.

**Comment by muescha** [comment] 2020-06-18 04:15
@wooorm it works well for my use case

what would be the best name for a debug plugin?

`unist-tool-debug` or `unist-tool-trace` or `retext-tool-debug`  (i think `vfile-` wont fit)

**Comment by wooorm** [comment] 2020-06-18 15:16
I’m going to close this because there is no change needed in this project.

> what would be the best name for a debug plugin?

If your project deals with unist, the strongly suggested prefix is `unist-util-`, e.g., `unist-util-trace-diff`.
If a project deals with remark, the suggested prefix is `remark-`, e.g., `remark-trace-diff`
If a project deals with unified, the suggested prefix is `unified-`, e.g., `unified-trace-diff`

Thanks for working on this!

**Closed as completed by wooorm** 2020-06-18 15:16 UTC
Labels: 👀 no/external

**Comment by muescha** [comment] 2020-06-18 15:32
> I’m going to close this because there is no change needed in this project.

👍 

> naming

it is mostly comparing the before tree and after tree saved in vfile and can used with unify as a `.use` plugin

**Comment by muescha** [comment] 2020-06-23 20:29
i think the name to go is: `unist-util-trace-diff` since it shows diffs of unist nodes
